kind: pipeline
type: docker
name: frontend

steps:
- name: build
  image: alpine
  commands:
  - echo compiling frontend
  - echo packaging frontend

---
kind: pipeline
type: docker
name: backend

steps:
- name: build
  image: alpine
  commands:
  - echo compiling backend
  - echo packaging backend

---
kind: gate
name: approval
type: docker

depends_on:
  - frontend
  - backend

---
kind: pipeline
type: docker
name: after

steps:
  - name: notify
    image: alpine
    commands:
      - echo notifying slack

depends_on:
  - approval
