kind: pipeline
type: docker
name: frontend

steps:
- name: build
  image: alpine
  commands:
  - echo compiling frontend
  - echo packaging frontend

---
kind: pipeline
type: docker
name: backend

steps:
- name: build
  image: alpine
  commands:
  - echo compiling backend
  - echo packaging backend

trigger:
  event:
  - promote
  target:
  - production
